type: form
title: "User Settings Form"
schema_cmd: "${APP_BIN} schema save-settings"
submit_cmd: "${APP_BIN} save-settings"
groups:
  - title: "Basic Information"
    fields:
      - name: username
        label: "Username"
        type: text
        required: true
      - name: email
        label: "Email"
        type: text
        placeholder: "user@example.com"
  - title: "Preferences"
    fields:
      - name: theme
        label: "Theme"
        type: select
        options: ["light", "dark", "auto"]
        default: "auto"
      - name: notifications
        label: "Enable Notifications"
        type: bool
        default: true
  - title: "Advanced"
    fields:
      - name: api_key
        label: "API Key"
        type: password
        placeholder: "Enter your API key..."