logo: "logo.txt"
header: "CHI TUI — Demo"
menu:
  - id: "hdr"
    title: "Demo Screens"
    widget: "header"
  - id: "welcome"
    title: "Welcome"
    # special-case: no command -> open Welcome screen
  - id: "autolist_enter"
    title: "Autoload (expand on Enter)"
    widget: "autoload_items"
    command: "${APP_BIN} list-items-slow"
    unwrap: "data.items"
    expand_on_enter: true
  - id: "hdr2"
    title: "Nested Demo"
    widget: "header"
  - id: "form_hello"
    title: "Hello (Form)"
    widget: "panel"
    panel_layout: "vertical"
    panel_size: "1:3"
    pane_b_yaml: "config/panel_b_form_hello.yaml"
  - id: "form_hello_auto"
    title: "Hello (Form Auto)"
    widget: "panel"
    panel_layout: "vertical"
    panel_size: "1:3"
    pane_b_yaml: "config/panel_b_form_hello_auto.yaml"
  - id: "form_tasks"
    title: "Tasks (Form Select)"
    widget: "panel"
    panel_layout: "vertical"
    panel_size: "1:3"
    pane_b_yaml: "config/panel_b_form_list_tasks.yaml"
  - id: "form_tasks_dyn"
    title: "Tasks (Dynamic Select)"
    widget: "panel"
    panel_layout: "vertical"
    panel_size: "1:3"
    pane_b_yaml: "config/panel_b_form_list_tasks_dyn.yaml"
  - id: "form_sum"
    title: "Sum Numbers (MultiSelect)"
    widget: "panel"
    panel_layout: "vertical"
    panel_size: "1:3"
    pane_b_yaml: "config/panel_b_form_sum.yaml"
  - id: "form_sum_auto"
    title: "Sum Numbers (Array)"
    widget: "panel"
    panel_layout: "vertical"
    panel_size: "1:3"
    pane_b_yaml: "config/panel_b_form_sum_auto.yaml"
  - id: "form_params_auto"
    title: "Numeric Params (Auto)"
    widget: "panel"
    panel_layout: "vertical"
    panel_size: "1:3"
    pane_b_yaml: "config/panel_b_form_params.yaml"
  - id: "form_text_auto"
    title: "Validate Text (Auto)"
    widget: "panel"
    panel_layout: "vertical"
    panel_size: "1:3"
    pane_b_yaml: "config/panel_b_form_text_auto.yaml"
  - id: "form_tags_dyn"
    title: "Choose Tags (Dynamic MultiSelect)"
    widget: "panel"
    panel_layout: "vertical"
    panel_size: "1:3"
    pane_b_yaml: "config/panel_b_form_tags_dyn.yaml"
  - id: "form_grouped"
    title: "Settings (Grouped)"
    widget: "panel"
    panel_layout: "vertical"
    panel_size: "1:3"
    pane_b_yaml: "config/panel_b_form_grouped_settings.yaml"
  - id: "form_grouped_auto"
    title: "Settings (Grouped Auto)"
    widget: "panel"
    panel_layout: "vertical"
    panel_size: "1:3"
    pane_b_yaml: "config/panel_b_form_grouped_settings_auto.yaml"
  - id: "form_password"
    title: "Password Field"
    widget: "panel"
    panel_layout: "vertical"
    panel_size: "1:3"
    pane_b_yaml: "config/panel_b_form_password.yaml"
  - id: "form_textarea"
    title: "Text Area"
    widget: "panel"
    panel_layout: "vertical"
    panel_size: "1:3"
    pane_b_yaml: "config/panel_b_form_textarea.yaml"
  - id: "markdown_demo"
    title: "Markdown (README)"
    widget: "markdown"
    path: "config/markdown_demo.md"
    pane_b_title: "Docs — Markdown README"
  - id: "watchdog_demo"
    title: "Watchdog (2 cmds)"
    widget: "watchdog"
    sequential: true
    pane_b_title: "Watchdog — demo run"
    auto_restart: false
    max_retries: 0
    restart_delay_ms: 1000
    stop_on_failure: true
    allowed_exit_codes: [0]
    commands:
      - "bash -lc 'echo One; sleep 1; echo Done 1'"
      - "bash -lc 'echo Two; sleep 1; echo Done 2'"
  - id: "watchdog_fail"
    title: "Watchdog (panic hook)"
    widget: "watchdog"
    sequential: true
    pane_b_title: "Watchdog — retries/panic"
    auto_restart: true
    max_retries: 2
    restart_delay_ms: 500
    stop_on_failure: true
    allowed_exit_codes: [0]
    on_panic_exit_cmd: "bash -lc 'echo PANIC HOOK TRIGGERED'"
    commands:
      - "bash -lc 'echo will fail; exit 1'"
      - "bash -lc 'echo never runs due to stop_on_failure'"
  - id: "watchdog_external"
    title: "Watchdog (external pgrep/pkill)"
    widget: "watchdog"
    pane_b_title: "Watchdog — External"
    # Try: in another terminal run:  sleep 99999 &
    # The watchdog below will detect it via pgrep and allow killing with 's'
    external_check_cmd: "bash -lc 'pgrep -f \"sleep 99999\" >/dev/null'"
    external_kill_cmd: "bash -lc 'pkill -f \"sleep 99999\"'"
  - id: "hdr3"
    title: "Watchdog Children"
    widget: "header"
  - id: "watchdog_children"
    title: "Children: Watchdog entries"
    # Static nested children to test child-level watchdog sessions and running indicator
    children:
      - title: "Child Watchdog A (parallel)"
        widget: "watchdog"
        pane_b_title: "Watchdog — Child A"
        sequential: false
        auto_restart: false
        max_retries: 0
        restart_delay_ms: 500
        stop_on_failure: false
        allowed_exit_codes: [0]
        stats:
          - { label: "INFO", regexp: "INFO|Done|done" }
        commands:
          - "bash -lc 'echo A1; sleep 3; echo Done A1'"
          - "bash -lc 'echo A2; sleep 4; echo Done A2'"
      - title: "Child Watchdog B (sequential)"
        widget: "watchdog"
        pane_b_title: "Watchdog — Child B"
        sequential: true
        auto_restart: false
        max_retries: 0
        restart_delay_ms: 500
        stop_on_failure: true
        allowed_exit_codes: [0]
        commands:
          - "bash -lc 'echo B1; sleep 2; echo Done B1'"
          - "bash -lc 'echo B2; sleep 2; echo Done B2'"
