header: "CHI TUI — Demo"
menu:
  - id: "hdr"
    title: "Demo Screens"
    widget: "header"
  - id: "welcome"
    title: "Welcome"
    # special-case: no command -> open Welcome screen
  - id: "autolist_enter"
    title: "Autoload (expand on Enter)"
    widget: "autoload_items"
    command: "${APP_BIN} list-items-slow"
    unwrap: "data.items"
    expand_on_enter: true
  - id: "hdr2"
    title: "Nested Demo"
    widget: "header"
  - id: "form_hello"
    title: "Hello (Form)"
    widget: "panel"
    panel_layout: "vertical"
    panel_size: "1:3"
    pane_b_yaml: "config/panel_b_form_hello.yaml"
  - id: "form_hello_auto"
    title: "Hello (Form Auto)"
    widget: "panel"
    panel_layout: "vertical"
    panel_size: "1:3"
    pane_b_yaml: "config/panel_b_form_hello_auto.yaml"
  - id: "form_tasks"
    title: "Tasks (Form Select)"
    widget: "panel"
    panel_layout: "vertical"
    panel_size: "1:3"
    pane_b_yaml: "config/panel_b_form_list_tasks.yaml"
  - id: "form_tasks_dyn"
    title: "Tasks (Dynamic Select)"
    widget: "panel"
    panel_layout: "vertical"
    panel_size: "1:3"
    pane_b_yaml: "config/panel_b_form_list_tasks_dyn.yaml"
  - id: "form_sum"
    title: "Sum Numbers (MultiSelect)"
    widget: "panel"
    panel_layout: "vertical"
    panel_size: "1:3"
    pane_b_yaml: "config/panel_b_form_sum.yaml"
  - id: "form_sum_auto"
    title: "Sum Numbers (Array)"
    widget: "panel"
    panel_layout: "vertical"
    panel_size: "1:3"
    pane_b_yaml: "config/panel_b_form_sum_auto.yaml"
  - id: "form_params_auto"
    title: "Numeric Params (Auto)"
    widget: "panel"
    panel_layout: "vertical"
    panel_size: "1:3"
    pane_b_yaml: "config/panel_b_form_params.yaml"
  - id: "form_text_auto"
    title: "Validate Text (Auto)"
    widget: "panel"
    panel_layout: "vertical"
    panel_size: "1:3"
    pane_b_yaml: "config/panel_b_form_text_auto.yaml"
  - id: "form_tags_dyn"
    title: "Choose Tags (Dynamic MultiSelect)"
    widget: "panel"
    panel_layout: "vertical"
    panel_size: "1:3"
    pane_b_yaml: "config/panel_b_form_tags_dyn.yaml"
  - id: "form_grouped"
    title: "Settings (Grouped)"
    widget: "panel"
    panel_layout: "vertical"
    panel_size: "1:3"
    pane_b_yaml: "config/panel_b_form_grouped_settings.yaml"
  - id: "form_grouped_auto"
    title: "Settings (Grouped Auto)"
    widget: "panel"
    panel_layout: "vertical"
    panel_size: "1:3"
    pane_b_yaml: "config/panel_b_form_grouped_settings_auto.yaml"
  - id: "form_password"
    title: "Password Field"
    widget: "panel"
    panel_layout: "vertical"
    panel_size: "1:3"
    pane_b_yaml: "config/panel_b_form_password.yaml"
  - id: "form_textarea"
    title: "Text Area"
    widget: "panel"
    panel_layout: "vertical"
    panel_size: "1:3"
    pane_b_yaml: "config/panel_b_form_textarea.yaml"
