type: form
title: "Tasks Form (Dynamic)"
fields:
  - name: "project"
    label: "Project"
    type: "select"
    options_cmd: "${APP_BIN} list-projects"
    unwrap: "data.items[].id/title"
    required: true
submit:
  command: "${APP_BIN} list-tasks"
