type: form
title: "Account (Password Demo)"
fields:
  - name: "username"
    label: "Username"
    type: "text"
    required: true
  - name: "password"
    label: "Password"
    type: "password"
    required: true

